### ISSUE TITLE
install failed because 404

### ISSUE THREAD

**Issue by scil** [javiertuya/dotnet-background#2]
yet support net 6?

```
C:\Program Files\dotnet\sdk\6.0.101\NuGet.targets(130,5): error :  unable from remote source “https://n
uget.org/FindPackagesById()?id='dotnetbackground'&semVerLevel=2.0.0”  search  “dotnetback
ground”  [C:\Users\i\AppData\Local\Temp\viap1ezy.uao\restore.csproj]
C:\Program Files\dotnet\sdk\6.0.101\NuGet.targets(130,5): error :   Response status code does not indicate success: 404 (Not Found). [C:\Users\i\AppData\Local\Temp\viap1ezy.uao\restore.csproj]
```

**Comment by javiertuya** [comment]
@scil A new version (1.2.0) is available now in nuget, it targets versions 3.1, 5.0 and 6.0.

Could you please check it? (I'm not sure if this was the issue because `?id='dotnetbackground'&semVerLevel=2.0.0` seems to indicate that you look for a higher version (2.0.0) than the available (now 1.2.0)

**Comment by scil** [comment]
thank you!

now it worked with version info
```
dotnet tool install --global DotnetBackground --version 1.2.0
```

it failed if I missed the `--version`

**Comment by javiertuya** [comment]
ok. Note: you need to specify the version because you had installed (and/or in the cache) the previous one.
